Dateformat: DateDElong
GroundWaterFrom: polygonfile
ResultFile: MUNout
#0 = hermes # 1 = csv
ResultFileFormat: 0
OutputIntervall: 1
InitSelection: 2
SoilFile: soil
SoilFileExtension: 'txt'
CropFileFormat: 'txt'
# Crop parameter file format (txt = hermes crop, yml = yaml format)
CropParameterFormat: 'txt'
WeatherFile: 'MET_%s.'
WeatherFileFormat: 0
WeatherFileSeperator: 1
WeatherFolder: "MUN"
WeatherRootFolder: "./weather/"
WeatherNoneValue: -99
WeatherNumHeader: 3
CorrectionPrecipitation: 0
ETpot: 3
CoastDistance: 90
CO2method: 2
CO2concentration: 401
CO2StomataInfluence: 1
StartYear: 2009
EndDate: "31122018"
AnnualOutputDate: "3112"
Latitude: 52.80
LeachingDepth: 8
OrganicMatterMineralProportion: 0.13
NDeposition: 15
PolygonGridFileName: poly
Fertilization: 100
VirtualDateFertilizerPrediction: '------'
KcFactorBareSoil: 0.6
AnnualAverageTemperature: 9.8
DivideCentury: 56
AutoSowingHarvest: 0
AutoFertilization: 0
AutoIrrigation: 0
AutoHarvest: 0
