name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15    
        
    - name: Debug
      run: |
        pwd
        echo ${GOPATH}
        echo ${GOROOT}
        
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        path: go/src/github.com/zalf-rpm/Hermes2Go

    - name: Install dependencies
      run: |
        go version
        go get -u gopkg.in/yaml.v2 
      env:
        GOPATH: /home/runner/work/Hermes2Go/Hermes2Go/go
    
    - name: Build
      working-directory: /home/runner/work/Hermes2Go/Hermes2Go/go/src/github.com/zalf-rpm/Hermes2Go
      run: |
       go build -v src/hermes2go
      env:
        GOPATH: /home/runner/work/Hermes2Go/Hermes2Go/go

      

