name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.work'  
    - run: go version
        
    - name: Install dependencies
      working-directory: ./src/hermes2go
      run: |
        go mod download
    
    - name: Build
      working-directory: ./src/hermes2go
      run: |
       go build -v -o hermes2go

      

